# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Add package repository from CDROM
# Parameter
#   dvd_mount_path: The CDROM device mount path
#
- name: "Set the local DVD repository name"
  ansible.builtin.set_fact:
    dvd_repo_name: "{{ guest_os_ansible_distribution }}-{{ guest_os_ansible_distribution_ver }}-DVD"

# Add repository from CDROM for RedHat and Suse family OS
- name: "Add repositories from CDROM for {{ vm_guest_os_distribution }}"
  when: guest_os_family in ['Suse', 'RedHat']
  block:
    # Find the dir having repodata
    - name: "Find repodata in {{ dvd_mount_path }}"
      ansible.builtin.command: "find {{ dvd_mount_path }} -name repodata"
      register: find_repodata_result
      delegate_to: "{{ vm_guest_ip }}"

    - name: "Check the CDROM device has repodata"
      ansible.builtin.assert:
        that:
          - find_repodata_result.stdout_lines is defined
          - find_repodata_result.stdout_lines | length >= 1
        fail_msg: "Not found repodata under {{ dvd_mount_path }}"
        success_msg: "Found repodata: {{ find_repodata_result.stdout_lines | default('') }}"

    - name: "Add package repositories from the CDROM device"
      include_tasks: add_repo_from_baseurl.yml
      vars:
        repo_name: "{{ dvd_repo_name }}-{{ repodata_path | dirname | basename }}"
        repo_baseurl: "{{ repodata_path | dirname }}"
        gpg_check: "{{ guest_os_ansible_distribution == 'RedHat' }}"
      with_items: "{{ find_repodata_result.stdout_lines }}"
      loop_control:
        loop_var: repodata_path
