# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   Collect dmesg and save output to a local file
# Parameters:
#   dmesg_opts: The dmesg command options. Default is empty.
#   dmesg_file_name: The file name saved dmesg output. Default is 'dmesg.txt'.
#   dmesg_error_check: True to check calltrace or errors in dmesg output. Default is false.
# Return:
#   dmesg_file_path: The file path saved dmesg output at localhost
#
- name: "Initialize the fact of dmesg output and file path at localhost"
  ansible.builtin.set_fact:
    dmesg_output: ""
    dmesg_file_path: "{{ current_test_log_folder }}/{{ dmesg_file_name | default('dmesg.txt') }}"

- name: "Print dmesg ring buffer"
  ansible.builtin.shell: "dmesg {{ dmesg_opts | default('') }}"
  changed_when: false
  ignore_errors: "{{ dmesg_error_check | default(false) }}"
  delegate_to: "{{ vm_guest_ip }}"
  no_log: true
  register: dmesg_result

- name: "Collect dmesg output to local"
  when:
    - dmesg_result.stdout_lines is defined
    - dmesg_result.stdout_lines | length > 0
  block:
    - name: "Set fact of dmest output"
      ansible.builtin.set_fact:
        dmesg_output: "{{ dmesg_result.stdout_lines }}"

    - name: "Save dmesg output to loal file"
      ansible.builtin.copy:
        dest: "{{ dmesg_file_path }}"
        content: "{{ dmesg_output }}"

    - name: "Check whether there is calltrace or errors in dmesg output"
      when: dmesg_error_check | default(false)
      block:
        - name: "Extract calltrace or errors from dmesg output"
          include_tasks: extract_errors_from_log.yml
          vars:
            local_log_path: "{{ dmesg_file_path }}"

        - name: "Display extracted calltrace or errors in dmesg output"
          ansible.builtin.debug:
            msg: "{{ errors_in_log }}"
          tags:
            - fail_message
          when: errors_in_log | length > 0
