# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Config package repositories for OS release
#
- name: "Set repositories proxy for installing package"
  include_tasks: ../utils/set_proxy.yml

- name: "Disable all existing repositories"
  include_tasks: ../utils/enable_disable_repo.yml
  vars:
    repo_op: "disable"
    repo_op_ignore_errors: true
  when: >-
    guest_os_ansible_distribution in ['RedHat', 'ProLinux'] or
    guest_os_family == 'Suse'

- name: "Add local repositories from ISO image for {{ vm_guest_os_distribution }}"
  include_tasks: ../utils/add_local_dvd_repo.yml
  when: guest_os_family in ['Suse', 'RedHat']

- name: "Add guest OS official online repositories for {{ vm_guest_os_distribution }}"
  include_tasks: ../utils/add_official_online_repo.yml
  when: guest_os_ansible_distribution not in ['SLES', 'SLED', 'RedHat', 'ProLinux']

- name: "Update packages metadata"
  include_tasks: ../utils/repo_update.yml
