# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Config package repositories for guest OS release
#
- name: "Disable all existing repositories for {{ vm_guest_os_distribution }}"
  include_tasks: enable_disable_repo.yml
  vars:
    repo_state: "disabled"
    repo_state_ignore_errors: true
  when: >-
    guest_os_ansible_distribution in ['RedHat', 'ProLinux', 'VMware Photon OS'] or
    guest_os_family == 'Suse'

# Local repositories might be invalid after VM reboot, so we will always configure them
# at necessary
- name: "Connect CDROM and add local repositories for {{ vm_guest_os_distribution }}"
  include_tasks: add_local_dvd_repo.yml
  when:
    - guest_os_family in ['Suse', 'RedHat']
    - os_installation_iso_list is defined
    - os_installation_iso_list | length > 0

# If online repositories have been configured before taking base snapshot
# We don't need to configure them again
- name: "Add guest OS official online repositories for {{ vm_guest_os_distribution }}"
  include_tasks: add_official_online_repo.yml
  when:
    - guest_os_ansible_distribution not in ['SLES', 'SLED', 'RedHat', 'ProLinux', 'FreeBSD']
    - guest_os_repos_enabled | default(false)

- name: "Update packages metadata"
  include_tasks: repo_update.yml
