# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get ESXi server advanced system settings"
  include_tasks: esxi_get_advanced_system_settings.yml

- name: "Display current state of guest IP hack on ESXi host"
  ansible.builtin.debug:
    msg: >-
      Current value of 'Net.GuestIPHack' is
      {{ esxi_advanced_system_settings['Net.GuestIPHack'] | default('') }}

- name: "Enable guest IP hack on ESXi host"
  include_tasks: esxi_set_advanced_system_settings.yml
  vars:
    esxi_host_config_options: {'Net.GuestIPHack': 1}
  when: >-
    esxi_advanced_system_settings['Net.GuestIPHack'] is undefined or
    esxi_advanced_system_settings['Net.GuestIPHack'] | string != "1"
