# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Extract call trace from a log file
# Parameters:
#   extract_log_path: The local log file path to extract call trace
# Return:
#   extracted_call_trace: The call trace extracted from the image file
#
- name: "Check log file path is an absolute path"
  ansible.builtin.assert:
    that:
      - extract_log_path is defined
      - extract_log_path
      - extract_log_path is ansible.builtin.abs
    fail_msg: "Parameter 'extract_log_path' must be set with a local absolute path"

- name: "Initialize the fact of extracted call trace"
  ansible.builtin.set_fact:
    extracted_call_trace: []

- name: "Extract call trace from log file"
  ansible.builtin.script: "../tools/extractor.py -t calltrace -f {{ extract_log_path }}"
  ignore_errors: True
  register: extract_calltrace_result

- name: "Set fact of extracted image text"
  ansible.builtin.set_fact:
    extracted_call_trace: "{{ extract_calltrace_result.stdout_lines | select }}"
  when:
    - extract_calltrace_result.stdout_lines is defined
    - extract_calltrace_result.stdout_lines | length > 0
