# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Extract text from an image file
# Parameters:
#   local_image_path: The local image file path to extract text
# Return:
#   text_in_image: The text extracted from the image file
#
- debug: var=local_image_path
- name: "Check local image file path is an absolute path"
  ansible.builtin.assert:
    that:
      - local_image_path is defined
      - local_image_path
      - local_image_path is ansible.builtin.abs
    fail_msg: "Parameter 'local_image_path' must be set with a local absolute path"

- name: "Initialize the fact of extracted image text"
  ansible.builtin.set_fact:
    text_in_image: []

- name: "Extract text from local image"
  ansible.builtin.script: "../tools/extractor.py -t text -f {{ local_image_path }}"
  ignore_errors: True
  register: extract_text_result

- name: "Set fact of extracted image text"
  ansible.builtin.set_fact:
    text_in_image: "{{ extract_text_result.stdout_lines | select }}"
  when:
    - extract_text_result.stdout_lines is defined
    - extract_text_result.stdout_lines | length > 0
