# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Create pre-install script, post-install script and unattend install config file
#
- name: "Initialize facts of autoinstall start message, pre and post install scripts"
  ansible.builtin.set_fact:
    autoinstall_start_msg: ""
    pre_install_script_path: ""
    post_install_script_path: ""

- name: "Create autoinstall pre-install and post-install scripts"
  when: unattend_installer in ["Ubuntu-Ubiquity", "Debian", "Pardus", "RHEL"]
  block:
    - name: "Set facts of autoinstall start message, pre and post install scripts"
      ansible.builtin.set_fact:
        autoinstall_start_msg: "Autoinstall is started"
        pre_install_script_file: "linux_pre_install.sh"
        pre_install_script_path: "{{ unattend_iso_cache }}/linux_pre_install.sh"
        post_install_script_file: "linux_post_install.sh"
        post_install_script_path: "{{ unattend_iso_cache }}/linux_post_install.sh"

    - name: "Create pre-install script from template"
      ansible.builtin.template:
        src: "templates/pre_install_scripts/{{ pre_install_script_file }}"
        dest: "{{ pre_install_script_path }}"
        mode: "0755"

    - name: "Create OS post-install script"
      ansible.builtin.template:
        src: "templates/post_install_scripts/{{ post_install_script_file }}"
        dest: "{{ post_install_script_path }}"
        mode: "0755"

- name: "Create OS unattend install config file"
  ansible.builtin.template:
    src: "{{ unattend_install_template }}"
    dest: "{{ new_unattend_install_conf }}"
    mode: "0644"
