# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Create unattend install config file, and pre-install, post-install scripts
# Parameters:
#   extractor_log_path: The local log file path to extract call trace
# Return:
#   extractor_call_trace: The call trace extracted from the image file
#
- name: "Initialize facts of pre-install and post-install scripts"
  ansible.builtin.set_fact:
    autoinstall_start_msg: "Autoinstall is started"
    pre_install_script_file: "linux_pre_install.sh"
    post_install_script_file: "linux_post_install.sh"
    pre_install_script_path: ""
    post_install_script_path: ""

- name: "Create OS pre-install script"
  when: pre_install_script_file
  block:
    - name: "Set fact of pre-install script path"
      ansible.builtin.set_fact:
        pre_install_script_path: "{{ unattend_iso_cache }}/{{ pre_install_script_file }}"

    - name: "Create pre-install script from template {{ pre_install_script_file }}"
      ansible.builtin.template:
        src: "templates/pre_install_scripts/{{ pre_install_script_file }}"
        dest: "{{ pre_install_script_path }}"
        mode: "0755"

- name: "Create OS post-install script"
  when: post_install_script_file
  block:
    - name: "Set fact of post-install script path"
      ansible.builtin.set_fact:
        post_install_script_path: "{{ unattend_iso_cache }}/{{ post_install_script_file }}"

    - name: "Create post-install script from template {{ post_install_script_file }}"
      ansible.builtin.template:
        src: "templates/post_install_scripts/{{ post_install_script_file }}"
        dest: "{{ post_install_script_path }}"
        mode: "0755"

- name: "Create OS unattend install config file"
  ansible.builtin.template:
    src: "{{ unattend_install_template }}"
    dest: "{{ new_unattend_install_conf }}"
    mode: "0644"
