# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Check open-vm-tools common and vmsvc plugins are loaded
#
- name: "Get loaded open-vm-tools plugins"
  ansible.builtin.shell: "lsof  2>/dev/null  | grep '/usr/local/lib/open-vm-tools/plugins' | awk '{print $NF}'"
  register: ovt_plugins_load_result
  ignore_errors: true
  delegate_to: "{{ vm_guest_ip }}"

- debug:
    msg: "{{ (ovt_plugins.common + ovt_plugins.vmsvc) | select('match', '.*.so') }}"
- name: "Set fact of not loaded open-vm-tools plugins"
  ansible.builtin.set_fact:
    ovt_plugins_unloaded: "{{ (ovt_plugins.common + ovt_plugins.vmsvc) | select('match', '.*.so') |
                              difference(ovt_plugins_load_result.stdout_lines | unique) }}"

- name: "Check required open-vm-tools files existing and plugins loaded"
  ansible.builtin.assert:
    that:
      - ovt_plugins_unloaded | length == 0
    fail_msg: "Failed to load open-vm-tools plugins {{ ','.join(ovt_plugins_unloaded) }} after installing from source."
    success_msg: "All of open-vm-tools common and vmsvc plugins are loaded after installing from source."
