# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Install open-vm-tools by building source tarball
#
- name: "Create files for installing open-vm-tools from source"
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: "{{ current_test_log_folder }}/{{ item }}"
    mode: "0755"
  with_items:
    - "{{ guest_os_ansible_system }}_ovt_build_config.yml"
    - "{{ guest_os_ansible_system }}_ovt_files_plugins.yml"

- name: "Set facts of open-vm-tools build config, files and plugins to be installed"
  ansible.builtin.set_fact:
    ovt_dependencies: "{{ _ovt_build_config.dependencies }}"
    ovt_configure_options: "{{ _ovt_build_config.configure_options | default([]) }}"
    ovt_files: "{{ (_ovt_installed_files | dict2items | map(attribute='value') | flatten) }}"
    ovt_plugins: "{{ _ovt_installed_files.plugins }}"
    ovt_vmusr_plugins: "{{ _ovt_installed_files.vmusr_plugins | default([]) }}"
  vars:
    _ovt_build_config: "{{ lookup('file', current_test_log_folder ~ '/ovt_build_config.yml') | from_yaml }}"
    _ovt_installed_files: "{{ lookup('file', current_test_log_folder ~ '/ovt_files_plugins.yml') | from_yaml }}"

- name: "Check facts of open-vm-tools dependencies, files and plugins"
  ansible.builtin.assert:
    that:
      - ovt_dependencies | length > 0
      - ovt_files | length > 0
      - ovt_plugins | length > 0
    fail_msg: >-
      Not found configs for open-vm-tools dependencies, files or plugins when installing from source on
      {{ guest_os_ansible_distribution }} {{ guest_os_ansible_distribution_ver }}

- name: "Display dependencies to be installed for building open-vm-tools"
  ansible.builtin.debug: var=ovt_dependencies

- name: "Install open-vm-tools build dependencies"
  include_tasks: ../utils/install_uninstall_package.yml
  vars:
    package_list: "{{ ovt_dependencies }}"

- name: "Set facts of open-vm-tools directory for downloading source"
  ansible.builtin.set_fact:
    guest_ovt_download_dir: "/root/ovt_source_{{ current_test_timestamp }}"

- name: "Create directory for downloading open-vm-tools source tarball"
  ansible.builtin.file:
    path: "{{ guest_ovt_download_dir }}"
    mode: "{{ dir_mode | default('0755') }}"
    state: directory
    recurse: true
  delegate_to: "{{ vm_guest_ip }}"

- name: "Download open-vm-tools source tarball"
  ansible.builtin.get_url:
    url: "{{ linux_ovt_tarball_url }}"
    dest: "{{ guest_ovt_download_dir }}"
    validate_certs: False
    mode: "0644"
  delegate_to: "{{ vm_guest_ip }}"
  register: ovt_tarball_download_result

- name: "Unarchive open-vm-tools source tarball"
  ansible.builtin.unarchive:
    src: "{{ ovt_tarball_download_result.dest }}"
    dest: "{{ guest_ovt_download_dir }}"
    remote_src: True
  delegate_to: "{{ vm_guest_ip }}"

- name: "Search open-vm-tools configure.ac file"
  ansible.builtin.shell: "find {{ guest_ovt_download_dir }} -name configure.ac"
  delegate_to: "{{ vm_guest_ip }}"
  register: find_configure_result

- name: "Check open-vm-tools configure.ac file exists"
  ansible.builtin.assert:
    that:
      - find_configure_result.rc is defined
      - find_configure_result.rc == 0
      - find_configure_result.stdout is defined
      - find_configure_result.stdout
    fail_msg: "The open-vm-tools configure.ac file doesn't exist"
    success_msg: "The open-vm-tools configure.ac file path is {{ find_configure_result.stdout }}"

- name: "Set fact of open-vm-tools source directory and installation log"
  ansible.builtin.set_fact:
    guest_ovt_source_dir: "{{ _ovt_src_dir }}"
    guest_ovt_install_log: "{{ _ovt_src_dir }}/ovt_install.log"
  vars:
    _ovt_src_dir: "{{ find_configure_result.stdout | replace('/configure.ac', '') }}"

- name: "Install open-vm-tools from source"
  ansible.builtin.shell: |
    echo ">>>Executing autoreconf" >{{ guest_ovt_install_log }};
    autoreconf -f -i >>{{ guest_ovt_install_log }};
    if [ $? -ne 0 ]; then exit 201; fi;

    echo ">>>Executing configure" >>{{ guest_ovt_install_log }};
    ./configure {{ ' '.join(ovt_configure_options) }}>>{{ guest_ovt_install_log }};
    if [ $? -ne 0 ]; then exit 202; fi;

    echo ">>>Executing make" >>{{ guest_ovt_install_log }};
    make >>{{ guest_ovt_install_log }};
    if [ $? -ne 0 ]; then exit 203; fi;

    echo ">>>Executing make install" >>{{ guest_ovt_install_log }};
    make install >>{{ guest_ovt_install_log }};
    if [ $? -ne 0 ]; then exit 204; fi;

    echo ">>>Executing ldconfig" >>{{ guest_ovt_install_log }};
    ldconfig >>{{ guest_ovt_install_log }};
  args:
    chdir: "{{ guest_ovt_source_dir }}"
  delegate_to: "{{ vm_guest_ip }}"
  register: ovt_src_install
  async: 600
  poll: 0

- name: "Check on async task for installing open-vm-tools"
  async_status:
    jid: "{{ ovt_src_install.ansible_job_id }}"
  delegate_to: "{{ vm_guest_ip }}"
  register: ovt_install_job_result
  until: ovt_install_job_result.finished
  retries: 60
  delay: 10

- name: "Check open-vm-tools required files are installed"
  include_tasks: check_ovt_files_exist.yml

