# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is to verify open-vm-tools installation by building source.
# If guest OS doesn't have open-vm-tools, this case will install open-vm-tools by building source.
# The source tarball can be downloaded from URL defined in linux_ovt_tarball_url.
# If it already has open-vm-tools installed and update_tools parameter is set True in vars/test.yml,
# it will reinstall open-vm-tools.
#
- name: ovt_verify_src_install
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Prepare for installing open-vm-tools"
          include_tasks: pre_ovt_install.yml

        - name: "Install open-vm-tools from source"
          include_tasks: install_ovt_from_source.yml

        - name: "Post actions after open-vm-tools installation"
          include_tasks: post_ovt_install.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
