# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Map VM guest OS release to guest id
# Parameters:
#   esxi_guest_ids: A list of ESXi supported guest ids
# Return:
#   expected_guest_id: The appropriate guest id for the guest OS type
#
- name: "Initialize facts for mapping guest id for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    map_guest_os_ansible_distribution: "{{ gos_name | replace('linux', 'Linux') }}"
    guest_os_release_name: "{{ guest_os_release.NAME }}"
    guest_os_release_major_version: "{{ guest_os_release.VERSION.split('.') | first }}"
    guest_os_release_id: "{{ guest_os_release.ID }}"
    matched_guest_ids: []
    expected_guest_id: ""

# Set guest id match pattern
# For un-versioned guest ids. For example,
# AlmaLinux, Fedora, FusionOS, Kylin Linux, MIRACLE LINUX, Pardus, ProLinux, Ubuntu, Rocky, etc
- name: "Set facts for matching guest ids for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    guest_id_match_pattern: "{{ '(?i)' ~ (guest_os_release_id|guest_os_release_name) ~ '\d*.*' expected_guest_id_suffix }} | lower"
#  when: guest_os_release_id in ['almalinux', 'fedora', 'fusionos', 'kylin', 'miraclelinux',
#                                'pardus', 'pl', 'ubuntu', 'rocky']

# Set guest id match pattern for versioned guest ids. For example,
- name: "Look for exactly matched guest id for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    mapped_guest_ids: "{{ esxi_guest_ids | select('match', guest_id_match_pattern) }}"

- meta: end_play
  
- name: "Set guest id for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    expected_guest_id: "ubuntu{{ expected_guest_id_suffix | replace('_', '') }}"
  when: guest_os_ansible_distribution == "ubuntu"

- name: "Set guest id for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    expected_guest_id: "vmwarePhoton64Guest"
  when:
    - guest_os_ansible_distribution == "photon"
    - "'vmwarePhoton64Guest' in esxi_guest_ids"
- block:
    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      ansible.builtin.set_fact:
        expected_guest_id: "rockylinux_64Guest"
      when: hardware_version | int >= 20

    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      ansible.builtin.set_fact:
        expected_guest_id: "other4xLinux64Guest"
      when: hardware_version | int < 20
  when: guest_os_ansible_distribution == "rocky"
- block:
    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      ansible.builtin.set_fact:
        expected_guest_id: "almalinux_64Guest"
      when: hardware_version | int >= 20

    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      ansible.builtin.set_fact:
        expected_guest_id: "other4xLinux64Guest"
      when: hardware_version | int < 20
  when: guest_os_ansible_distribution == "almalinux"

- name: "Set guest id for {{ vm_guest_os_distribution }}"
  when: guest_os_ansible_distribution == "miraclelinux"
  block:
    # To reset when new id is available for miraclelinux9 in vSphere Next
    # Templates used for GOSC testing: other4xLinux64Guest works on 7.0, asianux8_64Guest enabled on 8.0 for GOSC
    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      when:
        - hardware_version | int >= 20
        - gos_major_version | int >= 8
      ansible.builtin.set_fact:
        expected_guest_id: "asianux8_64Guest"
    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      when: hardware_version | int < 20
      ansible.builtin.set_fact:
        expected_guest_id: "other4xLinux64Guest"

- block:
    - fail:
        msg: "{{ vm_guest_os_distribution }} is not supported for creating VMLibrary template"
      when: gos_major_version is not match('^[0-9]+$')

    - block:
        - name: "Set fact of ESXi supported {{ guest_os_ansible_distribution }} guest ids"
          ansible.builtin.set_fact:
            supported_guest_ids: "{{ esxi_guest_ids | select('match', map_guest_os_ansible_distribution ~ '.*64Guest') }}"

        - name: "Set fact of ESXi supported {{ guest_os_ansible_distribution }} guest versions"
          ansible.builtin.set_fact:
            supported_guest_versions: "{{ supported_guest_ids | map('replace', '64Guest', '') | map('regex_search', '\\d+') | map('replace', 'None', 0) }}"
      when: gos_bit == '64bit'

    - block:
        - name: "Set fact of ESXi supported {{ guest_os_ansible_distribution }} guest ids"
          ansible.builtin.set_fact:
            supported_guest_ids: "{{ esxi_guest_ids | select('match', map_guest_os_ansible_distribution ~ '.*Guest') | reject('match', '.*64Guest') }}"

        - name: "Set fact of ESXi supported {{ guest_os_ansible_distribution }} guest versions"
          ansible.builtin.set_fact:
            supported_guest_versions: "{{ supported_guest_ids | map('replace', 'Guest', '') | map('regex_search', '\\d+') | map('replace', 'None', 0) }}"

      when: gos_bit != '64bit'

    - name: "Get closest guest id version"
      ansible.builtin.set_fact:
        closest_guest_version: "{{ supported_guest_versions | select('<=', gos_major_version) | max }}"

    - name: "Get closest guest id index in supported_guest_ids"
      ansible.builtin.set_fact:
        guest_id_index: "{{ lookup('ansible.utils.index_of', supported_guest_versions, '==', closest_guest_version)  }}"

    - name: "Set guest id for {{ vm_guest_os_distribution }}"
      ansible.builtin.set_fact:
        expected_guest_id: "{{ supported_guest_ids[guest_id_index | int] }}"
  when: guest_os_ansible_distribution in ['rhel', 'centos', 'oraclelinux', 'sles', 'debian']

- block:
    - fail:
        msg: "Fail the task due to {{ vm_guest_os_distribution }} is not supported for auto install"
      when: >
        (guest_os_ansible_distribution == 'windows' and
         (gos_major_version is not match('^[0-9]+$') or
          gos_major_version | int < 10)) or
        (guest_os_ansible_distribution == 'windows-server' and
         ((gos_major_version is not match('^[0-9]+$') and
          gos_major_version | lower != 'sac') or
          gos_major_version | int < 2019))

    - block:
        - name: "Set default guest id for {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            expected_guest_id: "windows9{{ expected_guest_id_suffix }}"
         
        - name: "Set guest id for {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            expected_guest_id: "windows11{{ expected_guest_id_suffix }}"
          when: ((gos_major_version | int >= 11) and (hardware_version | int >= 20))
      when: (guest_os_ansible_distribution == 'windows')

    - block:
        - name: "Set default guest id for {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            expected_guest_id: "windows9Server{{ expected_guest_id_suffix | replace('_', '') }}"

        - name: "Find more proper guest id for {{ vm_guest_os_distribution }}"
          ansible.builtin.set_fact:
            expected_guest_id: "{{ item }}{{ expected_guest_id_suffix }}"
          when: item ~ expected_guest_id_suffix in esxi_guest_ids
          with_items: ['windows2019srv', 'windows2019srvNext', 'windows2022srvNext']
      when: guest_os_ansible_distribution == 'windows-server'
  when: guest_os_ansible_distribution in ['windows', 'windows-server']

- name: "Set guest id for {{ vm_guest_os_distribution }}"
  ansible.builtin.set_fact:
    expected_guest_id: "{% if gos_bit == '64bit' %}other4xLinux64Guest{% else %}other4xLinuxGuest{% endif %}"
  when: guest_os_ansible_distribution not in ['windows', 'windows-server', 'rhel', 'centos', 'oraclelinux', 'sles', 'debian', 'ubuntu', 'photon','rocky','almalinux','miraclelinux']

- name: "Print selected guest id for creating new VM with {{ vm_guest_os_distribution }}"
  debug: var=expected_guest_id
